server:
  port: 8080
spring:
  #DataSource
  datasource:
    url: jdbc:mysql://47.107.50.13:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: dev
    password: "Cz!&170428"
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #JPA
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop #每次启动tomcat都删除数据库
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5 # 使用HTML5标准
    cache: false # 热部署静态文件,禁止使用缓存
    encoding: UTF-8
  h2:
    console:
      enabled: true #打开缓存数据库H2的控制台
  data:
    elasticsearch:
      cluster-nodes: 47.107.50.13:9300 # 远程服务
      properties:
        transport:
          tcp:
            connect_timeout: 120s # 设置连接超时时间
# 文件服务器的接口的位置
file:
  server:
    url: http://47.107.50.13:8081/upload