server:
  port: 8080
spring:
  #DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #JPA
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop #每次启动tomcat都删除数据库
  thymeleaf:
    mode: HTML5 # 使用HTML5标准
    cache: false # 热部署静态文件,禁止使用缓存
    encoding: UTF-8
  h2:
    console:
      enabled: true #打开缓存数据库H2的控制台
  data:
    elasticsearch:
      cluster-nodes: localhost:9300 # 远程服务
      properties:
        transport:
          tcp:
            connect_timeout: 120s # 设置连接超时时间
# 文件服务器的接口的位置
file:
  server:
    url: http://localhost:8081/upload